engines:
  tailor:
    enabled: true
    config: .tailor.yml
  shellcheck:
    enabled: true
  fixme:
    enabled: true
  bundler-audit:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
  - "**.swift"
  - "Gemfile.lock"
