module_name: CitySimCore
author_name: 'Steve Rohrlack'

clean: true
min_acl: internal
swift_version: 2.2
github_url: https://github.com/SteveRohrlack/CitySimCore
source-directory: ./src/
module: CitySimCore
xcodebuild-arguments -scheme,CitySimCoreiOS

#custom_categories:
#  - name: Configuration
#    children:
#    - Config
