language: objective-c
osx_image: xcode7.3
xcode_project: CitySimCore.xcodeproj
xcode_scheme: 
    - CitySimCoreiOS
    - CitySimCoreMacOS
xcode_sdk: 
    - iphonesimulator9.3
    - macosx10.11
matrix:
     exclude:
           - xcode_scheme: CitySimCoreiOS
             xcode_sdk: macosx10.11
           - xcode_scheme: CitySimCoreMacOS
             xcode_sdk: iphonesimulator9.3
cache: bundler
addons:
    code_climate:
        repo_token: ff68225fb2a64fb00c8af7f2bf998a68bedeef11232fa13fc99896b8a0c102f3
